# Generated by Django 5.2.15 on 2026-06-20 15:19

import signature.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('signature', signature.fields.SignatureField(blank=True, editable=True, field_type='blob', null=True)),
                ('initials', signature.fields.SignatureField(blank=True, editable=True, field_type='blob', initial_mode=5, null=True)),
                ('signature_image', signature.fields.SignatureField(blank=True, field_type='image')),
                ('initials_image', signature.fields.SignatureField(blank=True, field_type='image', initial_mode=5, upload_to='signatures/initials/')),
            ],
            options={
                'verbose_name': 'Signed Document',
                'verbose_name_plural': 'Signed Documents',
            },
        ),
    ]
