# Generated by Django 6.0.3 on 2026-06-20 15:23

import signature.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedDocumentNoRedraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('signature', signature.fields.SignatureField(blank=True, editable=True, field_type='blob', null=True)),
                ('initials', signature.fields.SignatureField(blank=True, editable=True, field_type='blob', initial_mode=5, null=True)),
                ('signature_image', signature.fields.SignatureField(blank=True, field_type='image', upload_to='signatures/no-redraw/')),
                ('initials_image', signature.fields.SignatureField(blank=True, field_type='image', initial_mode=5, upload_to='signatures/no-redraw/initials/')),
            ],
            options={
                'verbose_name': 'Signed Document (no redraw)',
                'verbose_name_plural': 'Signed Documents (no redraw)',
            },
        ),
    ]
